export const DASHBOARD_ACTION_TYPES = {
  FETCH_STOCKLIST_SUCCESS : 'FETCH_STOCKLIST_SUCCESS',
  FETCH_MARKET_TRENDS_SUCCESS : 'FETCH_MARKET_TRENDS_SUCCESS',
  FETCH_STOCKS_ABOVE_EMA_SUCCESS: 'FETCH_STOCKS_ABOVE_EMA_SUCCESS'
};
