export const STOCK_DETAIL_ACTION_TYPES = {
  FETCH_STOCK_DETAIL_SUCCESS : 'FETCH_STOCKDETAIL_SUCCESS',
  REMOVE_STOCK_DETAIL_DATA: 'REMOVE_STOCK_DETAIL_DATA',
  FETCH_STOCKLIST_SUCCESS : 'FETCH_STOCKLIST_SUCCESS',
};
